class PaystackBankCode {
  List<String> paystackBankNames = [
    "9mobile 9Payment Service Bank",
    "Abbey Mortgage Bank",
    "Above Only MFB",
    "Abulesoro MFB",
    "Access Bank",
    "Access Bank (Diamond)",
    "Accion Microfinance Bank",
    "Aella MFB",
    "AG Mortgage Bank",
    "Ahmadu Bello University Microfinance Bank",
    "Airtel Smartcash PSB",
    "AKU Microfinance Bank",
    "Akuchukwu Microfinance Bank Limited",
    "ALAT by WEMA",
    "Alternative bank",
    "Amegy Microfinance Bank",
    "Amju Unique MFB",
    "Aramoko MFB",
    "ASO Savings and Loans",
    "Assets Microfinance Bank",
    "Astrapolaris MFB LTD",
    "AVUENEGBE MICROFINANCE BANK",
    "AWACASH MICROFINANCE BANK",
    "AZTEC MICROFINANCE BANK LIMITED",
    "Bainescredit MFB",
    "Banc Corp Microfinance Bank",
    "BANKIT MICROFINANCE BANK LTD",
    "BANKLY MFB",
    "Baobab Microfinance Bank",
    "BellBank Microfinance Bank",
    "Benysta Microfinance Bank Limited",
    "Beststar Microfinance Bank",
    "BOLD MFB",
    "Bosak Microfinance Bank",
    "Bowen Microfinance Bank",
    "Branch International Finance Company Limited",
    "BuyPower MFB",
    "Carbon",
    "Cashbridge Microfinance Bank Limited",
    "CASHCONNECT MFB",
    "CEMCS Microfinance Bank",
    "Chanelle Microfinance Bank Limited",
    "Chikum Microfinance bank",
    "Citibank Nigeria",
    "CITYCODE MORTAGE BANK",
    "Consumer Microfinance Bank",
    "Corestep MFB",
    "Coronation Merchant Bank",
    "County Finance Limited",
    "Credit Direct Limited",
    "Crescent MFB",
    "Crust Microfinance Bank",
    "CRUTECH MICROFINANCE BANK LTD",
    "Davenport MICROFINANCE BANK",
    "Dot Microfinance Bank",
    "EBSU Microfinance Bank",
    "Ecobank Nigeria",
    "Ekimogun MFB",
    "Ekondo Microfinance Bank",
    "EXCEL FINANCE BANK",
    "Eyowo",
    "Fairmoney Microfinance Bank",
    "Fedeth MFB",
    "Fidelity Bank",
    "Firmus MFB",
    "First Bank of Nigeria",
    "First City Monument Bank",
    "FIRST ROYAL MICROFINANCE BANK",
    "FIRSTMIDAS MFB",
    "FirstTrust Mortgage Bank Nigeria",
    "FSDH Merchant Bank Limited",
    "FUTMINNA MICROFINANCE BANK",
    "Garun Mallam MFB",
    "Gateway Mortgage Bank LTD",
    "Globus Bank",
    "Goldman MFB",
    "GoMoney",
    "GOOD SHEPHERD MICROFINANCE BANK",
    "Goodnews Microfinance Bank",
    "Greenwich Merchant Bank",
    "GROOMING MICROFINANCE BANK",
    "GTI MFB",
    "Guaranty Trust Bank",
    "Hackman Microfinance Bank",
    "Hasal Microfinance Bank",
    "HopePSB",
    "IBANK Microfinance Bank",
    "IBBU MFB",
    "Ibile Microfinance Bank",
    "Ikoyi Osun MFB",
    "Ilaro Poly Microfinance Bank",
    "Imowo MFB",
    "IMPERIAL HOMES MORTAGE BANK",
    "Infinity MFB",
    "Infinity trust  Mortgage Bank",
    "ISUA MFB",
    "Jaiz Bank",
    "Kadpoly MFB",
    "KANOPOLY MFB",
    "Keystone Bank",
    "Kolomoni MFB",
    "KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)",
    "Kredi Money MFB LTD",
    "Kuda Bank",
    "Lagos Building Investment Company Plc.",
    "Letshego Microfinance Bank",
    "Links MFB",
    "Living Trust Mortgage Bank",
    "LOMA MFB",
    "Lotus Bank",
    "MAINSTREET MICROFINANCE BANK",
    "Mayfair MFB",
    "Mint MFB",
    "Money Master PSB",
    "Moniepoint MFB",
    "MTN Momo PSB",
    "MUTUAL BENEFITS MICROFINANCE BANK",
    "NDCC MICROFINANCE BANK",
    "NET MICROFINANCE BANK",
    "Nigerian Navy Microfinance Bank Limited",
    "Nombank MFB",
    "NOVA BANK",
    "Novus MFB",
    "NPF MICROFINANCE BANK",
    "NSUK MICROFINANACE BANK",
    "OLUCHUKWU MICROFINANCE BANK LTD",
    "OPay Digital Services Limited (OPay)",
    "Optimus Bank Limited",
    "Paga",
    "PalmPay",
    "Parallex Bank",
    "Parkway - ReadyCash",
    "PATHFINDER MICROFINANCE BANK LIMITED",
    "Paystack-Titan",
    "Peace Microfinance Bank",
    "PECANTRUST MICROFINANCE BANK LIMITED",
    "Personal Trust MFB",
    "Petra Mircofinance Bank Plc",
    "Pettysave MFB",
    "PFI FINANCE COMPANY LIMITED",
    "Platinum Mortgage Bank",
    "Pocket App",
    "Polaris Bank",
    "Polyunwana MFB",
    "PremiumTrust Bank",
    "Prospa Capital Microfinance Bank",
    "PROSPERIS FINANCE LIMITED",
    "Providus Bank",
    "QuickFund MFB",
    "Rand Merchant Bank",
    "RANDALPHA MICROFINANCE BANK",
    "Refuge Mortgage Bank",
    "REHOBOTH MICROFINANCE BANK",
    "Rephidim Microfinance Bank",
    "Rigo Microfinance Bank Limited",
    "ROCKSHIELD MICROFINANCE BANK",
    "Rubies MFB",
    "Safe Haven MFB",
    "SAGE GREY FINANCE LIMITED",
    "Shield MFB",
    "Signature Bank Ltd",
    "Solid Allianze MFB",
    "Solid Rock MFB",
    "Sparkle Microfinance Bank",
    "Stanbic IBTC Bank",
    "Standard Chartered Bank",
    "STANFORD MICROFINANCE BANK",
    "STATESIDE MICROFINANCE BANK",
    "STB Mortgage Bank",
    "Stellas MFB",
    "Sterling Bank",
    "Suntrust Bank",
    "Supreme MFB",
    "TAJ Bank",
    "Tangerine Money",
    "TENN",
    "Titan Bank",
    "TransPay MFB",
    "U&C Microfinance Bank Ltd (U AND C MFB)",
    "UCEE MFB",
    "Uhuru MFB",
    "Ultraviolet Microfinance Bank",
    "Unaab Microfinance Bank Limited",
    "Unical MFB",
    "Unilag Microfinance Bank",
    "UNIMAID MICROFINANCE BANK",
    "Union Bank of Nigeria",
    "United Bank For Africa",
    "Unity Bank",
    "Uzondu Microfinance Bank Awka Anambra State",
    "Vale Finance Limited",
    "VFD Microfinance Bank Limited",
    "Waya Microfinance Bank",
    "Wema Bank",
    "Weston Charis MFB",
    "Xpress Wallet",
    "Yes MFB",
    "Zenith Bank"
  ];

  Map<String, String> paystackBankCodes = {
    "9mobile 9Payment Service Bank": "120001",
    "Abbey Mortgage Bank": "404",
    "Above Only MFB": "51204",
    "Abulesoro MFB": "51312",
    "Access Bank": "044",
    "Access Bank (Diamond)": "063",
    "Accion Microfinance Bank": "602",
    "Aella MFB": "50315",
    "AG Mortgage Bank": "90077",
    "Ahmadu Bello University Microfinance Bank": "50036",
    "Airtel Smartcash PSB": "120004",
    "AKU Microfinance Bank": "51336",
    "Akuchukwu Microfinance Bank Limited": "090561",
    "ALAT by WEMA": "035A",
    "Alternative bank": "000304",
    "Amegy Microfinance Bank": "090629",
    "Amju Unique MFB": "50926",
    "Aramoko MFB": "50083",
    "ASO Savings and Loans": "401",
    "Assets Microfinance Bank": "50092",
    "Astrapolaris MFB LTD": "MFB50094",
    "AVUENEGBE MICROFINANCE BANK": "090478",
    "AWACASH MICROFINANCE BANK": "51351",
    "AZTEC MICROFINANCE BANK LIMITED": "51337",
    "Bainescredit MFB": "51229",
    "Banc Corp Microfinance Bank": "50117",
    "BANKIT MICROFINANCE BANK LTD": "50572",
    "BANKLY MFB": "51341",
    "Baobab Microfinance Bank": "MFB50992",
    "BellBank Microfinance Bank": "51100",
    "Benysta Microfinance Bank Limited": "51267",
    "Beststar Microfinance Bank": "50123",
    "BOLD MFB": "50725",
    "Bosak Microfinance Bank": "650",
    "Bowen Microfinance Bank": "50931",
    "Branch International Finance Company Limited": "FC40163",
    "BuyPower MFB": "50645",
    "Carbon": "565",
    "Cashbridge Microfinance Bank Limited": "51353",
    "CASHCONNECT MFB": "865",
    "CEMCS Microfinance Bank": "50823",
    "Chanelle Microfinance Bank Limited": "50171",
    "Chikum Microfinance bank": "312",
    "Citibank Nigeria": "023",
    "CITYCODE MORTAGE BANK": "070027",
    "Consumer Microfinance Bank": "50910",
    "Corestep MFB": "50204",
    "Coronation Merchant Bank": "559",
    "County Finance Limited": "FC40128",
    "Credit Direct Limited": "40119",
    "Crescent MFB": "51297",
    "Crust Microfinance Bank": "090560",
    "CRUTECH MICROFINANCE BANK LTD": "50216",
    "Davenport MICROFINANCE BANK": "51334",
    "Dot Microfinance Bank": "50162",
    "EBSU Microfinance Bank": "50922",
    "Ecobank Nigeria": "050",
    "Ekimogun MFB": "50263",
    "Ekondo Microfinance Bank": "098",
    "EXCEL FINANCE BANK": "090678",
    "Eyowo": "50126",
    "Fairmoney Microfinance Bank": "51318",
    "Fedeth MFB": "50298",
    "Fidelity Bank": "070",
    "Firmus MFB": "51314",
    "First Bank of Nigeria": "011",
    "First City Monument Bank": "214",
    "FIRST ROYAL MICROFINANCE BANK": "090164",
    "FIRSTMIDAS MFB": "51333",
    "FirstTrust Mortgage Bank Nigeria": "413",
    "FSDH Merchant Bank Limited": "501",
    "FUTMINNA MICROFINANCE BANK": "832",
    "Garun Mallam MFB": "MFB51093",
    "Gateway Mortgage Bank LTD": "812",
    "Globus Bank": "00103",
    "Goldman MFB": "090574",
    "GoMoney": "100022",
    "GOOD SHEPHERD MICROFINANCE BANK": "090664",
    "Goodnews Microfinance Bank": "50739",
    "Greenwich Merchant Bank": "562",
    "GROOMING MICROFINANCE BANK": "51276",
    "GTI MFB": "50368",
    "Guaranty Trust Bank": "058",
    "Hackman Microfinance Bank": "51251",
    "Hasal Microfinance Bank": "50383",
    "HopePSB": "120002",
    "IBANK Microfinance Bank": "51211",
    "IBBU MFB": "51279",
    "Ibile Microfinance Bank": "51244",
    "Ikoyi Osun MFB": "50439",
    "Ilaro Poly Microfinance Bank": "50442",
    "Imowo MFB": "50453",
    "IMPERIAL HOMES MORTAGE BANK": "415",
    "Infinity MFB": "50457",
    "Infinity trust  Mortgage Bank": "070016",
    "ISUA MFB": "090701",
    "Jaiz Bank": "301",
    "Kadpoly MFB": "50502",
    "KANOPOLY MFB": "51308",
    "Keystone Bank": "082",
    "Kolomoni MFB": "899",
    "KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)": "100025",
    "Kredi Money MFB LTD": "50200",
    "Kuda Bank": "50211",
    "Lagos Building Investment Company Plc.": "90052",
    "Letshego Microfinance Bank": "090420",
    "Links MFB": "50549",
    "Living Trust Mortgage Bank": "031",
    "LOMA MFB": "50491",
    "Lotus Bank": "303",
    "MAINSTREET MICROFINANCE BANK": "090171",
    "Mayfair MFB": "50563",
    "Mint MFB": "50304",
    "Money Master PSB": "946",
    "Moniepoint MFB": "50515",
    "MTN Momo PSB": "120003",
    "MUTUAL BENEFITS MICROFINANCE BANK": "090190",
    "NDCC MICROFINANCE BANK": "090679",
    "NET MICROFINANCE BANK": "51361",
    "Nigerian Navy Microfinance Bank Limited": "51142",
    "Nombank MFB": "50072",
    "NOVA BANK": "561",
    "Novus MFB": "51371",
    "NPF MICROFINANCE BANK": "50629",
    "NSUK MICROFINANACE BANK": "51261",
    "OLUCHUKWU MICROFINANCE BANK LTD": "50697",
    "OPay Digital Services Limited (OPay)": "999992",
    "Optimus Bank Limited": "107",
    "Paga": "100002",
    "PalmPay": "999991",
    "Parallex Bank": "104",
    "Parkway - ReadyCash": "311",
    "PATHFINDER MICROFINANCE BANK LIMITED": "090680",
    "Paystack-Titan": "100039",
    "Peace Microfinance Bank": "50743",
    "PECANTRUST MICROFINANCE BANK LIMITED": "51226",
    "Personal Trust MFB": "51146",
    "Petra Mircofinance Bank Plc": "50746",
    "Pettysave MFB": "MFB51452",
    "PFI FINANCE COMPANY LIMITED": "050021",
    "Platinum Mortgage Bank": "268",
    "Pocket App": "00716",
    "Polaris Bank": "076",
    "Polyunwana MFB": "50864",
    "PremiumTrust Bank": "105",
    "Prospa Capital Microfinance Bank": "50739",
    "PROSPERIS FINANCE LIMITED": "050023",
    "Providus Bank": "101",
    "QuickFund MFB": "51293",
    "Rand Merchant Bank": "502",
    "RANDALPHA MICROFINANCE BANK": "090496",
    "Refuge Mortgage Bank": "90067",
    "REHOBOTH MICROFINANCE BANK": "50761",
    "Rephidim Microfinance Bank": "50994",
    "Rigo Microfinance Bank Limited": "51286",
    "ROCKSHIELD MICROFINANCE BANK": "50767",
    "Rubies MFB": "125",
    "Safe Haven MFB": "51113",
    "SAGE GREY FINANCE LIMITED": "40165",
    "Shield MFB": "50582",
    "Signature Bank Ltd": "106",
    "Solid Allianze MFB": "51062",
    "Solid Rock MFB": "50800",
    "Sparkle Microfinance Bank": "51310",
    "Stanbic IBTC Bank": "221",
    "Standard Chartered Bank": "068",
    "STANFORD MICROFINANCE BANK": "090162",
    "STATESIDE MICROFINANCE BANK": "50809",
    "STB Mortgage Bank": "070022",
    "Stellas MFB": "51253",
    "Sterling Bank": "232",
    "Suntrust Bank": "100",
    "Supreme MFB": "50968",
    "TAJ Bank": "302",
    "Tangerine Money": "51269",
    "TENN": "51403",
    "Titan Bank": "102",
    "TransPay MFB": "090708",
    "U&C Microfinance Bank Ltd (U AND C MFB)": "50840",
    "UCEE MFB": "090706",
    "Uhuru MFB": "51322",
    "Ultraviolet Microfinance Bank": "51080",
    "Unaab Microfinance Bank Limited": "50870",
    "Unical MFB": "50871",
    "Unilag Microfinance Bank": "51316",
    "UNIMAID MICROFINANCE BANK": "50875",
    "Union Bank of Nigeria": "032",
    "United Bank For Africa": "033",
    "Unity Bank": "215",
    "Uzondu Microfinance Bank Awka Anambra State": "50894",
    "Vale Finance Limited": "050020",
    "VFD Microfinance Bank Limited": "566",
    "Waya Microfinance Bank": "51355",
    "Wema Bank": "035",
    "Weston Charis MFB": "51386",
    "Xpress Wallet": "100040",
    "Yes MFB": "594",
    "Zenith Bank": "057"
  };
}
